package adventofcode.week1;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import adventofcode.helpers.Tower;

public class Day7
{
	public Tower getRoot(List<Tower> towers)
	{
		Optional<Tower> rootOfCurrent = Optional.of(towers.get(0));
		Tower currentTower = towers.get(0);
		while (rootOfCurrent.isPresent())
		{
			rootOfCurrent = currentTower.getParent(towers);
			if (rootOfCurrent.isPresent())
			{
				currentTower = rootOfCurrent.get();
			}
		}

		return currentTower;
	}

	public static List<Tower> getExampleTowers()
	{
		List<Tower> towers = new ArrayList<Tower>();
		towers.add(new Tower("pbga", 66));
		towers.add(new Tower("xhth", 57));
		towers.add(new Tower("ebii", 61));
		towers.add(new Tower("havc", 66));
		towers.add(new Tower("ktlj", 57));
		towers.add(new Tower("fwft", 72, new String[] { "ktlj", "cntj", "xhth" }));
		towers.add(new Tower("qoyq", 66));
		towers.add(new Tower("padx", 45, new String[] { "pbga", "havc", "qoyq" }));
		towers.add(new Tower("tknk", 41, new String[] { "ugml", "padx", "fwft" }));
		towers.add(new Tower("jptl", 61));
		towers.add(new Tower("ugml", 68, new String[] { "gyxo", "ebii", "jptl" }));
		towers.add(new Tower("gyxo", 61));
		towers.add(new Tower("cntj", 57));
		return towers;
	}

	public static List<Tower> getAssignmentTowers()
	{
		List<Tower> towers = new ArrayList<Tower>();
		towers.add(new Tower("jlbcwrl", 93));
		towers.add(new Tower("fzqsahw", 256, new String[] { "lybovx", "pdmhva" }));
		towers.add(new Tower("rxivjo", 206, new String[] { "mewof", "hrncqs", "qgfstpq" }));
		towers.add(new Tower("jhldwxy", 26));
		towers.add(new Tower("bpzxjg", 62));
		towers.add(new Tower("lahain", 70));
		towers.add(new Tower("enbnfw", 39));
		towers.add(new Tower("uzsytm", 45));
		towers.add(new Tower("gmcsy", 16));
		towers.add(new Tower("rsqyvy", 99));
		towers.add(new Tower("lsbsfge", 163, new String[] { "ldxgz", "mksan" }));
		towers.add(new Tower("husmkc", 29));
		towers.add(new Tower("ootidjt", 63));
		towers.add(new Tower("pjhry", 38));
		towers.add(new Tower("kvlbq", 22));
		towers.add(new Tower("rdrad", 6, new String[] { "gwyfm", "fozyip", "uotzz", "fmkkz" }));
		towers.add(new Tower("oqbfkud", 470, new String[] { "rnbqhk", "mepez", "mnksdxf", "mjsck", "bbfaxid", "nglea" }));
		towers.add(new Tower("pgchejz", 54, new String[] { "ifelr", "rdkvtq" }));
		towers.add(new Tower("zzjyw", 91));
		towers.add(new Tower("yftjdo", 12));
		towers.add(new Tower("eqnvty", 87));
		towers.add(new Tower("adbolgz", 38));
		towers.add(new Tower("rcjqzp", 65, new String[] { "mkyam", "apdfe", "avzljw", "hxgidsw", "fkgxak", "wzsbsf", "woczl" }));
		towers.add(new Tower("ksrsmjx", 72));
		towers.add(new Tower("wfdlusw", 49));
		towers.add(new Tower("rpoep", 38));
		towers.add(new Tower("jesiypo", 78));
		towers.add(new Tower("jjxvns", 56));
		towers.add(new Tower("syyfs", 35));
		towers.add(new Tower("otplae", 91));
		towers.add(new Tower("epsjj", 17));
		towers.add(new Tower("utgxfsh", 959, new String[] { "mupbrv", "borbd", "jmieet" }));
		towers.add(new Tower("pxzdv", 15));
		towers.add(new Tower("ksybvgt", 213));
		towers.add(new Tower("tywzhc", 243));
		towers.add(new Tower("sbdja", 16));
		towers.add(new Tower("ctynr", 63));
		towers.add(new Tower("vwbjuvx", 99));
		towers.add(new Tower("aidknm", 97));
		towers.add(new Tower("qlgme", 21, new String[] { "ehjnzn", "cdbkci" }));
		towers.add(new Tower("zetvslt", 99));
		towers.add(new Tower("ferzy", 65));
		towers.add(new Tower("dssdiok", 97));
		towers.add(new Tower("gexdb", 6));
		towers.add(new Tower("bbzmsv", 87));
		towers.add(new Tower("mepez", 126, new String[] { "uqvyau", "witovp" }));
		towers.add(new Tower("pubtsp", 70, new String[] { "jlvwibm", "uvvdw", "okmqiy" }));
		towers.add(new Tower("gjcxbx", 44));
		towers.add(new Tower("mogwb", 84));
		towers.add(new Tower("qwiekvk", 65));
		towers.add(new Tower("kwbovke", 74));
		towers.add(new Tower("offjbb", 15, new String[] { "dvoja", "jteju", "wuybunc", "qzpzi" }));
		towers.add(new Tower("cwdmlj", 86));
		towers.add(new Tower("ojpok", 88));
		towers.add(new Tower("lytcy", 2662, new String[] { "bkmvwp", "uyrwi" }));
		towers.add(new Tower("antcinm", 178, new String[] { "dmthn", "ycacj", "wkhggv" }));
		towers.add(new Tower("kstvq", 69));
		towers.add(new Tower("ibysnvc", 79));
		towers.add(new Tower("xulwh", 71));
		towers.add(new Tower("zgqzrc", 459, new String[] { "wlajxb", "mfywm", "jqmlxr" }));
		towers.add(new Tower("uyrwi", 11));
		towers.add(new Tower("qirjqsm", 96));
		towers.add(new Tower("fnoteku", 2482, new String[] { "mbezs", "kcuygjx", "bymkeq", "opsqjx" }));
		towers.add(new Tower("leeyi", 88));
		towers.add(new Tower("pcodkpi", 95));
		towers.add(new Tower("tetdx", 224, new String[] { "nshbwn", "rpoep", "fbqpk" }));
		towers.add(new Tower("ajhctd", 18));
		towers.add(new Tower("yhzuh", 72));
		towers.add(new Tower("dmvjz", 39));
		towers.add(new Tower("zdgwmi", 24));
		towers.add(new Tower("vprkzya", 37));
		towers.add(new Tower("ipryqov", 24));
		towers.add(new Tower("pdxylvu", 86, new String[] { "etscle", "bqtawf" }));
		towers.add(new Tower("ehrqn", 23, new String[] { "njabgq", "fyzeso", "jrgwnfh", "fxasat" }));
		towers.add(new Tower("ekszr", 148, new String[] { "gnmydtk", "wchxl" }));
		towers.add(new Tower("izkaqg", 26));
		towers.add(new Tower("lovypfn", 53));
		towers.add(new Tower("sztqzfl", 98));
		towers.add(new Tower("ckwopo", 43, new String[] { "yurfpj", "bgrxlxe", "tohrp" }));
		towers.add(new Tower("muksdck", 48, new String[] { "gwtcgyo", "tfpuqgs" }));
		towers.add(new Tower("tlfsn", 21));
		towers.add(new Tower("hrvztx", 57));
		towers.add(new Tower("psulm", 1838, new String[] { "rhbouej", "urhlfju", "obfet" }));
		towers.add(new Tower("dbufjl", 95, new String[] { "faihy", "oyamw" }));
		towers.add(new Tower("ucfhxsv", 65));
		towers.add(new Tower("ietfhkq", 31));
		towers.add(new Tower("psvjtka", 29));
		towers.add(new Tower("wzxei", 51));
		towers.add(new Tower("swurfm", 64));
		towers.add(new Tower("oybwhs", 18));
		towers.add(new Tower("dmdiy", 1601, new String[] { "lazjlns", "ygvol", "rljjjo", "whnjtp", "jilomb" }));
		towers.add(new Tower("jteju", 54));
		towers.add(new Tower("rdnpoms", 177, new String[] { "eskdbe", "fbhidp", "xtkxwd" }));
		towers.add(new Tower("rdhwx", 62));
		towers.add(new Tower("hxgidsw", 332, new String[] { "fukgfu", "skkatyg" }));
		towers.add(new Tower("pcewixh", 109, new String[] { "iekurr", "xspxxb" }));
		towers.add(new Tower("gsiypfp", 1146, new String[] { "bhwca", "qhcolun" }));
		towers.add(new Tower("igpabio", 53, new String[] { "mlqxueo", "lhsncv" }));
		towers.add(new Tower("vdjmhb", 39));
		towers.add(new Tower("pwdpe", 42, new String[] { "leeyi", "rhlpt", "dtexqt", "skpcerk" }));
		towers.add(new Tower("ciejakr", 43, new String[] { "hcqnhm", "anmeg", "melsryt" }));
		towers.add(new Tower("yehxck", 2391, new String[] { "boygd", "kayqqz", "iajslqp" }));
		towers.add(new Tower("sofve", 139));
		towers.add(new Tower("asifeu", 278, new String[] { "rtsajcq", "dcouu" }));
		towers.add(new Tower("mgqfa", 75, new String[] { "cipgxee", "jscjw" }));
		towers.add(new Tower("kbppnh", 99));
		towers.add(new Tower("apwsmv", 31));
		towers.add(new Tower("dzjyzd", 39));
		towers.add(new Tower("uobgj", 488, new String[] { "akidv", "sofve", "wblhx" }));
		towers.add(new Tower("qngfv", 8));
		towers.add(new Tower("kledju", 95));
		towers.add(new Tower("besihsl", 86));
		towers.add(new Tower("zqnmsyb", 73));
		towers.add(new Tower("csqfv", 14));
		towers.add(new Tower("ubgrma", 1059, new String[] { "ymhxg", "yvxuom", "aeyykn" }));
		towers.add(new Tower("ufyqf", 77));
		towers.add(new Tower("llventw", 308, new String[] { "lsbsfge", "itxycu", "nddymc" }));
		towers.add(new Tower("zfhwfsw", 53));
		towers.add(new Tower("kigdvl", 31));
		towers.add(new Tower("fiufzkb", 1194, new String[] { "ysigfem", "bchfd", "hgsmlsi" }));
		towers.add(new Tower("vaubjz", 233, new String[] { "erfnrn", "gqzva", "goxfpk" }));
		towers.add(new Tower("yhpiqn", 99));
		towers.add(new Tower("wzsbsf", 222, new String[] { "mwztduj", "hkpvwpa" }));
		towers.add(new Tower("mjaol", 281, new String[] { "dnazkh", "jkamtqv" }));
		towers.add(new Tower("mufnw", 106, new String[] { "yxdld", "obkhwze", "nkssh" }));
		towers.add(new Tower("mhapqqy", 16));
		towers.add(new Tower("brztp", 27));
		towers.add(new Tower("ebmjz", 68, new String[] { "xfydt", "eqnvty" }));
		towers.add(new Tower("hkjwio", 322, new String[] { "hdzxuz", "zdgwmi", "ipryqov" }));
		towers.add(new Tower("eszxg", 18));
		towers.add(new Tower("qwzac", 908, new String[] { "uiioczf", "qjdpk", "ylpuaf" }));
		towers.add(new Tower("ndsub", 75));
		towers.add(new Tower("xcqwjrm", 63));
		towers.add(new Tower("glsrg", 74, new String[] { "maiimn", "ufyqf" }));
		towers.add(new Tower("mtcxdod", 80));
		towers.add(new Tower("ygmhxm", 129, new String[] { "pljyyn", "njdmj" }));
		towers.add(new Tower("ijcojo", 1042, new String[] { "dxboqki", "ikplh", "pubtsp", "omergh" }));
		towers.add(new Tower("urhlfju", 249, new String[] { "csqfv", "rnddnj" }));
		towers.add(new Tower("lgefkp", 17));
		towers.add(new Tower("bmmmp", 90));
		towers.add(new Tower("rjzrh", 360, new String[] { "hbkujf", "mzwbtsa", "oywob", "dmxhbe" }));
		towers.add(new Tower("khiom", 117, new String[] { "hpaggeh", "lqumiws" }));
		towers.add(new Tower("zlgpmfs", 143, new String[] { "ilxfa", "nhpcp" }));
		towers.add(new Tower("fozyip", 293, new String[] { "kvlbq", "pfqbht" }));
		towers.add(new Tower("ylpuaf", 64, new String[] { "mdzkkjf", "tfdbdq", "kiauwpn" }));
		towers.add(new Tower("xekimqs", 65));
		towers.add(new Tower("bekxoxk", 87));
		towers.add(new Tower("zybeuh", 197, new String[] { "wonxzkm", "jzuvrtp" }));
		towers.add(new Tower("pudyrbw", 76));
		towers.add(new Tower("bcyarwn", 65));
		towers.add(new Tower("saowgr", 367, new String[] { "gbnxgny", "krmphks", "yftjdo", "zmpwz" }));
		towers.add(new Tower("tgmle", 73, new String[] { "prcjhey", "thzwwh", "cxhipq", "tgvpi" }));
		towers.add(new Tower("ezxsv", 90, new String[] { "qzqyveb", "dfmlo" }));
		towers.add(new Tower("rayez", 17));
		towers.add(new Tower("ujjpxe", 56));
		towers.add(new Tower("efsrz", 93));
		towers.add(new Tower("xaifomj", 53));
		towers.add(new Tower("ayury", 23));
		towers.add(new Tower("zavef", 69));
		towers.add(new Tower("qonfiro", 190, new String[] { "cotvk", "evqkdq" }));
		towers.add(new Tower("puurcu", 1689, new String[] { "awagc", "ajhctd" }));
		towers.add(new Tower("omergh", 208));
		towers.add(new Tower("padxpdx", 192, new String[] { "psvjtka", "husmkc" }));
		towers.add(new Tower("cxhipq", 92));
		towers.add(new Tower("jhgsgy", 39));
		towers.add(new Tower("leyiz", 74, new String[] { "fvfek", "njrfnvt" }));
		towers.add(new Tower("kdcvwyf", 52));
		towers.add(new Tower("zyympz", 887, new String[] { "pxteg", "amnoi", "amzwex" }));
		towers.add(new Tower("jbbmcxg", 34));
		towers.add(new Tower("uvmqarq", 751, new String[] { "muyodod", "nclwgga", "oeqvt" }));
		towers.add(new Tower("duepwu", 683, new String[] { "hbueku", "zbcra", "yxtjx" }));
		towers.add(new Tower("aatagmv", 44));
		towers.add(new Tower("zsvuw", 11));
		towers.add(new Tower("fynniwm", 35));
		towers.add(new Tower("fjzpjk", 88, new String[] { "uvsny", "aatagmv" }));
		towers.add(new Tower("rulhhsl", 90));
		towers.add(new Tower("fcscdg", 276, new String[] { "twvib", "skjtvyz", "oybwhs", "rdmggka" }));
		towers.add(new Tower("vwotlbl", 61));
		towers.add(new Tower("ijyoy", 24));
		towers.add(new Tower("jpenh", 186, new String[] { "kdcvwyf", "rjxvbkb" }));
		towers.add(new Tower("qzpzi", 54));
		towers.add(new Tower("nshbwn", 38));
		towers.add(new Tower("foyfb", 50));
		towers.add(new Tower("kbyot", 337, new String[] { "jhldwxy", "izkaqg" }));
		towers.add(new Tower("bhxdhmr", 65));
		towers.add(new Tower("netsm", 53));
		towers.add(new Tower("tgffx", 75, new String[] { "kstvq", "cjmfqbo" }));
		towers.add(new Tower("msthql", 7));
		towers.add(new Tower("hgscccv", 62));
		towers.add(new Tower("dbnelj", 212, new String[] { "jzcmf", "sqiac", "ijyoy", "jjqguew" }));
		towers.add(new Tower("jxfqev", 99));
		towers.add(new Tower("elmog", 32));
		towers.add(new Tower("ygvol", 202, new String[] { "mszzq", "tzzdbi" }));
		towers.add(new Tower("gjrqs", 159, new String[] { "iprkb", "cgouh" }));
		towers.add(new Tower("rabxkov", 84));
		towers.add(new Tower("wenii", 79, new String[] { "qsrpqe", "zdhqhh", "jpenh", "hwrxn", "vtvnn", "mpgixa", "fbjbwv" }));
		towers.add(new Tower("jkqvg", 28));
		towers.add(new Tower("kzdugfh", 90));
		towers.add(new Tower("mhkcp", 17));
		towers.add(new Tower("tfhdccw", 93));
		towers.add(new Tower("qzakfh", 62));
		towers.add(new Tower("hrncqs", 12));
		towers.add(new Tower("tzmndkd", 221, new String[] { "lixsvp", "ofyxhb" }));
		towers.add(new Tower("cjmfqbo", 69));
		towers.add(new Tower("ikplh", 98, new String[] { "bqifoq", "pjedtl" }));
		towers.add(new Tower("berje", 87));
		towers.add(new Tower("ikbqz", 9));
		towers.add(new Tower("avzljw", 234, new String[] { "vdbihjp", "zavef" }));
		towers.add(new Tower("ibiwh", 26, new String[] { "ndsub", "moihbcu" }));
		towers.add(new Tower("vdvadz", 38));
		towers.add(new Tower("yirnxk", 158, new String[] { "lgefkp", "rayez" }));
		towers.add(new Tower("vbnlfuo", 169, new String[] { "pppxrv", "rdhwx" }));
		towers.add(new Tower("lgxjr", 238, new String[] { "mhkba", "bsrkr" }));
		towers.add(new Tower("ynayo", 71));
		towers.add(new Tower("uvvdw", 46));
		towers.add(new Tower("udkyxw", 48));
		towers.add(new Tower("zotwsb", 170, new String[] { "wlufwnr", "frksv" }));
		towers.add(new Tower("tohdgsa", 30));
		towers.add(new Tower("bqtawf", 45));
		towers.add(new Tower("wrfxdc", 25));
		towers.add(new Tower("vjxmbzm", 69));
		towers.add(new Tower("opmmmd", 32, new String[] { "pcodkpi", "xhonf" }));
		towers.add(new Tower("hkpvwpa", 75));
		towers.add(new Tower("uflldd", 39));
		towers.add(new Tower("oelrlp", 23));
		towers.add(new Tower("lptkbzc", 151, new String[] { "unvje", "bzsiwp" }));
		towers.add(new Tower("ecdieu", 23));
		towers.add(new Tower("pxhwecw", 57));
		towers.add(new Tower("ryulu", 61));
		towers.add(new Tower("uplweb", 127, new String[] { "bpzxjg", "utivde" }));
		towers.add(new Tower("wblhx", 97, new String[] { "xayglgm", "pddllsa" }));
		towers.add(new Tower("grcox", 91));
		towers.add(new Tower("xergqq", 99));
		towers.add(new Tower("tgujvov", 59, new String[] { "rhpco", "ojpok", "trbnpf" }));
		towers.add(new Tower("sdnkg", 1381, new String[] { "gyutarg", "gcwcs", "mfjeyx" }));
		towers.add(new Tower("oydxsh", 67));
		towers.add(new Tower("pxihdrd", 50));
		towers.add(new Tower("cizehi", 7));
		towers.add(new Tower("zhopeqm", 80));
		towers.add(new Tower("frksv", 89));
		towers.add(new Tower("qvbfob", 266, new String[] { "oejqkp", "ocgkcxp" }));
		towers.add(new Tower("ldfsxw", 17));
		towers.add(new Tower("wltpv", 260, new String[] { "nlndxah", "etyyw" }));
		towers.add(new Tower("pddteg", 52, new String[] { "lwwyx", "mhnlgyl", "mvfhc", "dzggd", "opqoq", "mufrkl", "inghbu" }));
		towers.add(new Tower("kybsigz", 80));
		towers.add(new Tower("hgsmlsi", 31, new String[] { "bqqwmry", "lqavsk" }));
		towers.add(new Tower("cbyvzkp", 99));
		towers.add(new Tower("tjpatnk", 44));
		towers.add(new Tower("srneoo", 11, new String[] { "dhlrq", "ivwcuc", "laxoeu" }));
		towers.add(new Tower("piouhkc", 95));
		towers.add(new Tower("tgfgem", 33));
		towers.add(new Tower("egrfvic", 49));
		towers.add(new Tower("jmieet", 137, new String[] { "ckwooig", "stkodp" }));
		towers.add(new Tower("cldbz", 15));
		towers.add(new Tower("gylsj", 52));
		towers.add(new Tower("ecoqyk", 35));
		towers.add(new Tower("pnhibed", 75, new String[] { "gmdsb", "gijtd" }));
		towers.add(new Tower("fksxl", 5));
		towers.add(new Tower("rhpco", 88));
		towers.add(new Tower("eklahxm", 51));
		towers.add(new Tower("ftzht", 8102, new String[] { "dmdiy", "sfrbkzf", "hlcnxe", "zwsrt" }));
		towers.add(new Tower("cykvxs", 84));
		towers.add(new Tower("ccckie", 201, new String[] { "tgkusb", "alztgi" }));
		towers.add(new Tower("hbueku", 10, new String[] { "ohcszyk", "szutvca" }));
		towers.add(new Tower("cztikzk", 174, new String[] { "wxdpcvv", "lpbayb" }));
		towers.add(new Tower("lprmau", 27, new String[] { "rqymw", "dssdiok", "dydwqz", "eyale" }));
		towers.add(new Tower("zorvynv", 176, new String[] { "mqybmn", "jaxidl" }));
		towers.add(new Tower("laxoeu", 88));
		towers.add(new Tower("nvvxl", 93));
		towers.add(new Tower("duophdw", 72));
		towers.add(new Tower("qjwfsfk", 11));
		towers.add(new Tower("tzzdbi", 8));
		towers.add(new Tower("kwmam", 184, new String[] { "wdybaj", "cyielpd", "hhifd", "gexdb" }));
		towers.add(new Tower("ujktzrv", 71));
		towers.add(new Tower("dvoja", 54));
		towers.add(new Tower("opsqjx", 71));
		towers.add(new Tower("hlrjgro", 63));
		towers.add(new Tower("oqjkafl", 32, new String[] { "iwyjkz", "auneqme", "awccm" }));
		towers.add(new Tower("vuyeiv", 65));
		towers.add(new Tower("qhmyi", 130, new String[] { "dvfuz", "scruak" }));
		towers.add(new Tower("tnayomw", 62));
		towers.add(new Tower("ezdhr", 179));
		towers.add(new Tower("ypfsjd", 60, new String[] { "rdmrzdv", "yhpiqn", "cbyvzkp" }));
		towers.add(new Tower("auneqme", 86));
		towers.add(new Tower("kabixkr", 73));
		towers.add(new Tower("jntohm", 41));
		towers.add(new Tower("oyamw", 65));
		towers.add(new Tower("utivde", 62));
		towers.add(new Tower("qhcolun", 76));
		towers.add(new Tower("qjcbye", 535, new String[] { "fetkt", "pcewixh", "vaubjz", "ojhlp", "mnvgaqh", "rcjiwg" }));
		towers.add(new Tower("rfdpm", 80, new String[] { "wcevmtt", "tlayc" }));
		towers.add(new Tower("ovvrx", 84));
		towers.add(new Tower("zdhqhh", 200, new String[] { "ylyef", "onogiv", "tohdgsa" }));
		towers.add(new Tower("ofidu", 349, new String[] { "pjxqt", "cytlm" }));
		towers.add(new Tower("zqmlv", 59));
		towers.add(new Tower("uzuawb", 47));
		towers.add(new Tower("unvje", 71));
		towers.add(new Tower("osbbt", 1214, new String[] { "gqmscj", "vyriv", "bkkop" }));
		towers.add(new Tower("tmyhhql", 51));
		towers.add(new Tower("zxson", 61));
		towers.add(new Tower("rhlllw", 11));
		towers.add(new Tower("xtkxwd", 17));
		towers.add(new Tower("lijeejc", 57, new String[] { "mgkkyx", "thzyz" }));
		towers.add(new Tower("crhho", 1255, new String[] { "rfcfgg", "chnfm", "tuekps" }));
		towers.add(new Tower("jqkaucw", 53));
		towers.add(new Tower("rerckg", 63));
		towers.add(new Tower("kgevjdx", 84));
		towers.add(new Tower("muyodod", 19, new String[] { "wolet", "zzjyw" }));
		towers.add(new Tower("zjzoo", 65));
		towers.add(new Tower("evqkdq", 91));
		towers.add(new Tower("mecyei", 75));
		towers.add(new Tower("bvfcsls", 227, new String[] { "knpwsi", "ypfsjd", "eilzvpr" }));
		towers.add(new Tower("ntabiof", 365, new String[] { "rfohgya", "yoqbgjb" }));
		towers.add(new Tower("gqmscj", 155, new String[] { "kjlmdi", "scaec" }));
		towers.add(new Tower("bkmvwp", 11));
		towers.add(new Tower("tuekps", 169));
		towers.add(new Tower("mksan", 18));
		towers.add(new Tower("apmdcz", 16));
		towers.add(new Tower("plumb", 89));
		towers.add(new Tower("gcmio", 126, new String[] { "ujjpxe", "jjxvns" }));
		towers.add(new Tower("uqvyau", 6));
		towers.add(new Tower("bdkoa", 125, new String[] { "ctynr", "tvnco" }));
		towers.add(new Tower("xseshzl", 76));
		towers.add(new Tower("mnpvutr", 39));
		towers.add(new Tower("lghzki", 27));
		towers.add(new Tower("citugfl", 14));
		towers.add(new Tower("vxgwku", 16));
		towers.add(new Tower("jwaskb", 251));
		towers.add(new Tower("olkopyn", 66, new String[] { "qjcbye", "cstgeia", "uojcup", "ycctk", "dkhuccj" }));
		towers.add(new Tower("jscjw", 72));
		towers.add(new Tower("xatyg", 71));
		towers.add(new Tower("xpfxwd", 8));
		towers.add(new Tower("jjjks", 7331, new String[] { "qpefm", "dlhiqh", "gtervu", "pcnroj", "jijwa", "bgbnlki" }));
		towers.add(new Tower("ewvvi", 53));
		towers.add(new Tower("ycbgx", 1531, new String[] { "tzmndkd", "fpynzz", "tywzhc" }));
		towers.add(new Tower("cstgeia", 613, new String[] { "ckwopo", "sjiel", "akwfu", "ehvqyl", "wtyfb", "gcmio" }));
		towers.add(new Tower("ursjc", 45));
		towers.add(new Tower("mabkbom", 57));
		towers.add(new Tower("lafoho", 250));
		towers.add(new Tower("xmvbzka", 49));
		towers.add(new Tower("oasspz", 67));
		towers.add(new Tower("epumc", 86, new String[] { "pcdjo", "rerckg", "dwknfpc" }));
		towers.add(new Tower("cyielpd", 6));
		towers.add(new Tower("lmqaxz", 146, new String[] { "ghobhlm", "qvvcx" }));
		towers.add(new Tower("ydqjoa", 84));
		towers.add(new Tower("zfkfhfn", 33, new String[] { "txapm", "pygfz", "ekszr", "nbivp", "wltpv", "jsjaxjk" }));
		towers.add(new Tower("sslltlv", 45));
		towers.add(new Tower("tifqyde", 2264, new String[] { "koxiwk", "psulm", "rcjqzp" }));
		towers.add(new Tower("vonzkut", 76, new String[] { "bdafpm", "nvlxqp", "gxsbt" }));
		towers.add(new Tower("blagy", 338));
		towers.add(new Tower("cluxnul", 15));
		towers.add(new Tower("kdevmnr", 77));
		towers.add(new Tower("cmxulaj", 44, new String[] { "mnkqevh", "mkbgt", "nrcbc" }));
		towers.add(new Tower("tygwtg", 25));
		towers.add(new Tower("wpnqifq", 11));
		towers.add(new Tower("jilomb", 68, new String[] { "uduan", "mecyei" }));
		towers.add(new Tower("kytnz", 52));
		towers.add(new Tower("gynfwly", 66, new String[] { "lynvd", "dxhcxko", "xaatl", "leulsg", "zworz", "fkbrmim", "jjjks" }));
		towers.add(new Tower("msfxkn", 130, new String[] { "ietfhkq", "kigdvl" }));
		towers.add(new Tower("wewzb", 164, new String[] { "yzptgez", "ctytfj" }));
		towers.add(new Tower("hdzxuz", 24));
		towers.add(new Tower("ghbfyqe", 5));
		towers.add(new Tower("hbkujf", 133, new String[] { "ukghke", "aplbnbx" }));
		towers.add(new Tower("iwsjla", 38));
		towers.add(new Tower("dnalt", 35));
		towers.add(new Tower("gmdsb", 75));
		towers.add(new Tower("pcnroj", 2553, new String[] { "oljci", "losdis", "sdnkg", "zchulv", "crhho" }));
		towers.add(new Tower("dzrkq", 94));
		towers.add(new Tower("cjcapa", 292));
		towers.add(new Tower("dzohgiq", 43));
		towers.add(new Tower("rhlpt", 88));
		towers.add(new Tower("dkvzre", 99, new String[] { "mieecfc", "nvdouwn", "dbnelj", "onlwq", "ayaouxu", "xrhsy", "bvrlaep" }));
		towers.add(new Tower("zpntow", 72));
		towers.add(new Tower("vohta", 58));
		towers.add(new Tower("jqmlxr", 173, new String[] { "eiyxf", "fydjnl" }));
		towers.add(new Tower("lxhkgs", 85));
		towers.add(new Tower("qoiuwmf", 1008, new String[] { "vbnlfuo", "wjyreb", "sdbksb", "lptkbzc", "wopfs", "khiom" }));
		towers.add(new Tower("btgrhku", 24));
		towers.add(new Tower("nnhsuja", 16));
		towers.add(new Tower("jgwvp", 84));
		towers.add(new Tower("vdpmvm", 28));
		towers.add(new Tower("iimfrx", 59));
		towers.add(new Tower("oyfma", 21));
		towers.add(new Tower("sqypc", 7));
		towers.add(new Tower("txapm", 272, new String[] { "isggu", "yookz" }));
		towers.add(new Tower("zhbiaq", 45, new String[] { "rqzfef", "kplegas", "ayejq", "xevhcxq" }));
		towers.add(new Tower("bkcghv", 35));
		towers.add(new Tower("yjakrqa", 70));
		towers.add(new Tower("lmwrf", 51));
		towers.add(new Tower("uwhjd", 94));
		towers.add(new Tower("bpphw", 49));
		towers.add(new Tower("vtvnn", 114, new String[] { "uadnb", "huunb" }));
		towers.add(new Tower("blmfs", 52));
		towers.add(new Tower("rtsajcq", 6));
		towers.add(new Tower("lazjlns", 190, new String[] { "xbyjur", "edjwkkk" }));
		towers.add(new Tower("rnddnj", 14));
		towers.add(new Tower("vobeup", 41));
		towers.add(new Tower("kifer", 53));
		towers.add(new Tower("jdzbqlz", 15));
		towers.add(new Tower("wlufwnr", 89));
		towers.add(new Tower("bqznix", 75, new String[] { "stiln", "duophdw", "yhzuh" }));
		towers.add(new Tower("aovlz", 45));
		towers.add(new Tower("dyrvvfn", 340, new String[] { "prxseo", "vxgwku" }));
		towers.add(new Tower("ukghke", 28));
		towers.add(new Tower("lnczb", 69, new String[] { "tzntd", "cfnce" }));
		towers.add(new Tower("qllluo", 57));
		towers.add(new Tower("asbzj", 89, new String[] { "yjxyb", "hsifo", "fhasacf", "vwojb", "gcbcyn" }));
		towers.add(new Tower("sruyra", 47));
		towers.add(new Tower("ohplzu", 58));
		towers.add(new Tower("fmkkz", 319, new String[] { "owigu", "ikbqz" }));
		towers.add(new Tower("zimrsr", 223, new String[] { "dxympe", "fhpaqmd", "ayury" }));
		towers.add(new Tower("cdbkci", 79));
		towers.add(new Tower("tchbf", 93));
		towers.add(new Tower("wdybaj", 6));
		towers.add(new Tower("bexvn", 39));
		towers.add(new Tower("rcsfkrb", 11));
		towers.add(new Tower("bgbnlki", 2277, new String[] { "oqbfkud", "qsqis", "xhyqtqz", "qorkez", "qwzac", "oewlch", "gsiypfp" }));
		towers.add(new Tower("zworz", 41633, new String[] { "ootkqm", "wfovakv", "inldh" }));
		towers.add(new Tower("dwknfpc", 63));
		towers.add(new Tower("xjcprt", 87));
		towers.add(new Tower("ghobhlm", 41));
		towers.add(new Tower("erfndpf", 89, new String[] { "kwbovke", "adxhax", "cipwzoy" }));
		towers.add(new Tower("setrric", 31));
		towers.add(new Tower("erggh", 197, new String[] { "fksxl", "ghbfyqe" }));
		towers.add(new Tower("pzksun", 873, new String[] { "vyozfv", "jxfqev", "kbppnh" }));
		towers.add(new Tower("pddllsa", 21));
		towers.add(new Tower("xeomb", 44, new String[] { "vuyeiv", "bwrpskq", "qwiekvk", "gxzkde" }));
		towers.add(new Tower("dfmlo", 80));
		towers.add(new Tower("guvuihw", 39));
		towers.add(new Tower("khqhd", 42));
		towers.add(new Tower("fphgbca", 59));
		towers.add(new Tower("fhasacf", 269, new String[] { "fovilf", "rjnzany" }));
		towers.add(new Tower("oyamsv", 38));
		towers.add(new Tower("kjjyu", 65));
		towers.add(new Tower("pfqbht", 22));
		towers.add(new Tower("amzwex", 218, new String[] { "vprkzya", "wxixtqj", "oktfn" }));
		towers.add(new Tower("lwljcg", 85));
		towers.add(new Tower("hpeaki", 35));
		towers.add(new Tower("rcjiwg", 35, new String[] { "odckjtb", "jlfgvr", "tdbne" }));
		towers.add(new Tower("ktazkb", 57));
		towers.add(new Tower("tgvpi", 92));
		towers.add(new Tower("sdhqlxw", 1239, new String[] { "eklahxm", "ejzeqxz", "kabcmf" }));
		towers.add(new Tower("aonfaf", 52));
		towers.add(new Tower("mlqxueo", 67));
		towers.add(new Tower("akidv", 21, new String[] { "cnvyxm", "fphgbca" }));
		towers.add(new Tower("bozlg", 67));
		towers.add(new Tower("ewpbnsk", 64));
		towers.add(new Tower("thzwwh", 92));
		towers.add(new Tower("tuieolg", 7624, new String[] { "ldnrw", "cfuqhip", "rjzrh" }));
		towers.add(new Tower("tzrppo", 51, new String[] { "tfhdccw", "kbses", "jlbcwrl", "efsrz" }));
		towers.add(new Tower("fbjbwv", 290));
		towers.add(new Tower("dmthn", 25));
		towers.add(new Tower("witovp", 6));
		towers.add(new Tower("ugjzag", 24));
		towers.add(new Tower("agliie", 844, new String[] { "qjaywg", "rridl", "myaiu", "antcinm", "izhdt" }));
		towers.add(new Tower("ebgdslc", 31));
		towers.add(new Tower("abmqz", 31));
		towers.add(new Tower("hsfjd", 21));
		towers.add(new Tower("ootkqm", 9535, new String[] { "uplweb", "bdkoa", "ehrqn", "fpqudx", "assuj", "rjguqr", "jwaskb" }));
		towers.add(new Tower("ldxgz", 18));
		towers.add(new Tower("atfhgyu", 57));
		towers.add(new Tower("hbzju", 71));
		towers.add(new Tower("rrywqx", 69));
		towers.add(new Tower("dxqqhhd", 188, new String[] { "pzewv", "oelrlp" }));
		towers.add(new Tower("ixtrjm", 92));
		towers.add(new Tower("njeff", 28));
		towers.add(new Tower("dxboqki", 78, new String[] { "nstdz", "ferzy" }));
		towers.add(new Tower("mnwefbn", 65));
		towers.add(new Tower("bugfhhx", 357, new String[] { "abbnh", "intfltq" }));
		towers.add(new Tower("qorkez", 1280, new String[] { "euqiok", "ibvaekj" }));
		towers.add(new Tower("anbcmt", 17));
		towers.add(new Tower("iprkb", 26));
		towers.add(new Tower("vflyupn", 34));
		towers.add(new Tower("ruwzkz", 362));
		towers.add(new Tower("xrxseqy", 94));
		towers.add(new Tower("mszzq", 8));
		towers.add(new Tower("thzyz", 77));
		towers.add(new Tower("xyxtm", 92));
		towers.add(new Tower("qeubhb", 65));
		towers.add(new Tower("fmtyy", 35));
		towers.add(new Tower("hpowmso", 1854, new String[] { "jhysc", "xeomb", "nzwxd" }));
		towers.add(new Tower("ywvmghy", 63));
		towers.add(new Tower("rridl", 131, new String[] { "nqvflzq", "vwotlbl" }));
		towers.add(new Tower("dydwqz", 97));
		towers.add(new Tower("mhnlgyl", 1185, new String[] { "qntstgd", "qzpgle", "aozygag" }));
		towers.add(new Tower("uycjl", 292, new String[] { "xcqvne", "ruxnrix" }));
		towers.add(new Tower("ohcszyk", 32));
		towers.add(new Tower("gtervu", 88, new String[] { "dkvzre", "awufxne", "osbbt", "ycbgx", "wdjzjlk" }));
		towers.add(new Tower("xcqvne", 35));
		towers.add(new Tower("moihbcu", 75));
		towers.add(new Tower("wpoga", 57));
		towers.add(new Tower("rjxvbkb", 52));
		towers.add(new Tower("bihsr", 21, new String[] { "kyjkjy", "hgscccv", "yonjpz" }));
		towers.add(new Tower("vmmjgy", 742, new String[] { "vdkxk", "yhyxv", "cpfbmv" }));
		towers.add(new Tower("gwnipjd", 24));
		towers.add(new Tower("brcpgz", 57));
		towers.add(new Tower("dczcz", 1862, new String[] { "wszghwt", "navhthp", "lsfggz" }));
		towers.add(new Tower("wmaywuo", 87));
		towers.add(new Tower("vrfkofp", 49));
		towers.add(new Tower("nrcbij", 64, new String[] { "pudyrbw", "ghdime", "xseshzl" }));
		towers.add(new Tower("yxtjx", 74));
		towers.add(new Tower("dnzdqz", 179));
		towers.add(new Tower("gxsbt", 58));
		towers.add(new Tower("oqrmida", 222, new String[] { "lixqwd", "dnalt" }));
		towers.add(new Tower("nddymc", 93, new String[] { "ewvvi", "netsm" }));
		towers.add(new Tower("iekurr", 71));
		towers.add(new Tower("tcghqr", 43, new String[] { "mnhojtk", "ruwzkz", "veksns", "wrochvi", "uycjl", "umtfn", "qgvsuqv" }));
		towers.add(new Tower("ikfihh", 140, new String[] { "tygwtg", "vlmhyer" }));
		towers.add(new Tower("ziypsz", 84));
		towers.add(new Tower("ehjnzn", 79));
		towers.add(new Tower("exwxepj", 175, new String[] { "jszpe", "guvuihw", "ykruy" }));
		towers.add(new Tower("capxp", 68));
		towers.add(new Tower("nhpcp", 34));
		towers.add(new Tower("qzpgle", 77, new String[] { "gwnipjd", "mrcoxnt" }));
		towers.add(new Tower("edjwkkk", 14));
		towers.add(new Tower("uteosk", 65));
		towers.add(new Tower("ofyxhb", 11));
		towers.add(new Tower("tulxgem", 213, new String[] { "mabkbom", "btcjg", "ktazkb", "evcdf" }));
		towers.add(new Tower("dkttrfw", 219, new String[] { "ahqfoz", "kytnz" }));
		towers.add(new Tower("mttvnpg", 9));
		towers.add(new Tower("tzntd", 59));
		towers.add(new Tower("euqiok", 9));
		towers.add(new Tower("wgypwo", 290, new String[] { "btgrhku", "aqkdlo" }));
		towers.add(new Tower("chnfm", 169));
		towers.add(new Tower("vlmhyer", 25));
		towers.add(new Tower("urjwj", 78));
		towers.add(new Tower("miijab", 49));
		towers.add(new Tower("faihy", 65));
		towers.add(new Tower("skkatyg", 20));
		towers.add(new Tower("zfnoo", 18));
		towers.add(new Tower("dcmxxd", 35));
		towers.add(new Tower("evnlr", 1175, new String[] { "erfndpf", "hicuenj", "zybeuh" }));
		towers.add(new Tower("qzqyveb", 80));
		towers.add(new Tower("wpdbejb", 90));
		towers.add(new Tower("trbnpf", 88));
		towers.add(new Tower("yxxpgv", 70));
		towers.add(new Tower("wyomko", 184, new String[] { "tgfgem", "clnkvox" }));
		towers.add(new Tower("dxhcxko", 45, new String[] { "ftzht", "ypsme", "rmtbjn", "pjyld" }));
		towers.add(new Tower("lixsvp", 11));
		towers.add(new Tower("mofkvq", 126, new String[] { "ejuiv", "abmqz", "xqobg" }));
		towers.add(new Tower("zqtkn", 79, new String[] { "ugjzag", "dtzyg" }));
		towers.add(new Tower("xhonf", 95));
		towers.add(new Tower("kiauwpn", 22));
		towers.add(new Tower("nmstp", 44));
		towers.add(new Tower("hsifo", 210, new String[] { "wfdlusw", "myonh", "qunldzi" }));
		towers.add(new Tower("whnjtp", 146, new String[] { "zswyy", "bmugsve" }));
		towers.add(new Tower("txkgx", 60));
		towers.add(new Tower("icjur", 76, new String[] { "lwaeqm", "rhdudt" }));
		towers.add(new Tower("fpynzz", 24, new String[] { "kepkgvf", "kabixkr", "jbexk" }));
		towers.add(new Tower("qunldzi", 49));
		towers.add(new Tower("ucxedq", 84));
		towers.add(new Tower("wndpfac", 55));
		towers.add(new Tower("hicuenj", 122, new String[] { "ootidjt", "hlrjgro", "ywvmghy" }));
		towers.add(new Tower("kkdaw", 65));
		towers.add(new Tower("dmxhbe", 141, new String[] { "myhrxc", "jbbivz", "behncf" }));
		towers.add(new Tower("borbd", 21, new String[] { "ujktzrv", "hbzju", "xulwh", "xatyg" }));
		towers.add(new Tower("adxhax", 74));
		towers.add(new Tower("zwsrt", 2544, new String[] { "xmvbzka", "egrfvic", "fovkc" }));
		towers.add(new Tower("hhqlfj", 81, new String[] { "xqgwwr", "zmlmsuf" }));
		towers.add(new Tower("jiuuhl", 78));
		towers.add(new Tower("dcouu", 6));
		towers.add(new Tower("yetcvhx", 71));
		towers.add(new Tower("rfcfgg", 28, new String[] { "sruyra", "bqmqbi", "uzuawb" }));
		towers.add(new Tower("pygfz", 92, new String[] { "kledju", "upevl" }));
		towers.add(new Tower("etscle", 45));
		towers.add(new Tower("pzjbbdd", 93));
		towers.add(new Tower("fjpgybt", 21));
		towers.add(new Tower("mjsck", 90, new String[] { "mkkpihe", "fmqjogk" }));
		towers.add(new Tower("cfuqhip", 57, new String[] { "ixkicz", "yqnihs", "vifwkwa" }));
		towers.add(new Tower("jkamtqv", 80));
		towers.add(new Tower("ulvncs", 172, new String[] { "bexvn", "jzsmy" }));
		towers.add(new Tower("cytlm", 46));
		towers.add(new Tower("axikbt", 9, new String[] { "tjffhqh", "mogwb", "cykvxs", "ydqjoa" }));
		towers.add(new Tower("lageym", 228));
		towers.add(new Tower("jmlznjh", 50));
		towers.add(new Tower("wszghwt", 160, new String[] { "brcpgz", "wryfov" }));
		towers.add(new Tower("yxdld", 38));
		towers.add(new Tower("fukgfu", 20));
		towers.add(new Tower("mjlnaz", 72, new String[] { "zcgfj", "jiuuhl" }));
		towers.add(new Tower("bchfd", 109, new String[] { "ccityq", "nmvvgr" }));
		towers.add(new Tower("ogvod", 1281, new String[] { "bihsr", "erggh", "dqgfb", "xguhm" }));
		towers.add(new Tower("gcxrx", 91));
		towers.add(new Tower("ttnnyy", 92, new String[] { "lhsccbq", "dpdjpal" }));
		towers.add(new Tower("kxflpnl", 16));
		towers.add(new Tower("ehvqyl", 192, new String[] { "zjgok", "ecdieu" }));
		towers.add(new Tower("lsfggz", 94, new String[] { "itttb", "wpdbejb" }));
		towers.add(new Tower("aacegb", 8));
		towers.add(new Tower("wxdpcvv", 8));
		towers.add(new Tower("viufoq", 25, new String[] { "bekxoxk", "wmaywuo" }));
		towers.add(new Tower("pqnte", 70));
		towers.add(new Tower("rmtbjn", 78, new String[] { "lytcy", "aiunuvn", "hfvhp", "dczcz", "kqaoir", "ekihql", "qkrydu" }));
		towers.add(new Tower("imjutr", 187, new String[] { "wgeig", "wqbhby" }));
		towers.add(new Tower("swpfak", 21));
		towers.add(new Tower("vmvxwar", 38));
		towers.add(new Tower("uxrrjqx", 205));
		towers.add(new Tower("mddejh", 441));
		towers.add(new Tower("fbhidp", 17));
		towers.add(new Tower("vunam", 90));
		towers.add(new Tower("rnbqhk", 62, new String[] { "rdwkvr", "oyamsv" }));
		towers.add(new Tower("bezvr", 55));
		towers.add(new Tower("kbses", 93));
		towers.add(new Tower("dqgfb", 43, new String[] { "hpuyku", "rycmr" }));
		towers.add(new Tower("uadnb", 88));
		towers.add(new Tower("dnrfjv", 55));
		towers.add(new Tower("wykkwa", 67));
		towers.add(new Tower("kyjkjy", 62));
		towers.add(new Tower("wrochvi", 150, new String[] { "kifer", "xaifomj", "usodrg", "jqkaucw" }));
		towers.add(new Tower("krmphks", 12));
		towers.add(new Tower("jbzaips", 36));
		towers.add(new Tower("qjaywg", 94, new String[] { "khpat", "jcpavmj", "bchlcqs" }));
		towers.add(new Tower("kayqqz", 77, new String[] { "kdqjj", "sbdja", "gmcsy" }));
		towers.add(new Tower("zjgok", 23));
		towers.add(new Tower("mrcoxnt", 24));
		towers.add(new Tower("wopfs", 159, new String[] { "oasspz", "zgssy" }));
		towers.add(new Tower("herqgqi", 36));
		towers.add(new Tower("zcdzv", 11));
		towers.add(new Tower("assuj", 137, new String[] { "atfhgyu", "pxhwecw" }));
		towers.add(new Tower("cvgbj", 48));
		towers.add(new Tower("lywkfsn", 127));
		towers.add(new Tower("cpfbmv", 204));
		towers.add(new Tower("scruak", 30));
		towers.add(new Tower("lsteeu", 162, new String[] { "tatubv", "rprjk", "tgblta", "uxrrjqx", "pweea", "sgieno" }));
		towers.add(new Tower("hhlxxzt", 96, new String[] { "ixtrjm", "tknmww", "cnbekc" }));
		towers.add(new Tower("gmwtl", 49));
		towers.add(new Tower("sjiel", 238));
		towers.add(new Tower("pweea", 51, new String[] { "eggmj", "clpekkm" }));
		towers.add(new Tower("cnnrj", 78));
		towers.add(new Tower("eilzvpr", 213, new String[] { "ksrsmjx", "zpntow" }));
		towers.add(new Tower("cipwzoy", 74));
		towers.add(new Tower("apdfe", 184, new String[] { "xrxseqy", "leegl" }));
		towers.add(new Tower("bkkop", 347));
		towers.add(new Tower("cuhrgp", 81, new String[] { "ohtply", "vrfkofp" }));
		towers.add(new Tower("kepkgvf", 73));
		towers.add(new Tower("odkzxae", 91));
		towers.add(new Tower("qmqrpcl", 92));
		towers.add(new Tower("bgrxlxe", 65));
		towers.add(new Tower("xqobg", 31));
		towers.add(new Tower("awccm", 86));
		towers.add(new Tower("slhitu", 27));
		towers.add(new Tower("dihzy", 79));
		towers.add(new Tower("jfdscql", 362, new String[] { "amrbhgv", "rfdpm", "ecxfenj", "dxqqhhd" }));
		towers.add(new Tower("eqsxuaq", 49));
		towers.add(new Tower("hlcnxe", 1998, new String[] { "fcpde", "zyniqni", "offjbb" }));
		towers.add(new Tower("pdmhva", 18));
		towers.add(new Tower("dtzyg", 24));
		towers.add(new Tower("xpker", 36));
		towers.add(new Tower("gqzva", 6));
		towers.add(new Tower("thqkxpl", 38));
		towers.add(new Tower("avelbqj", 31));
		towers.add(new Tower("mrigsjh", 55));
		towers.add(new Tower("ltbpi", 17, new String[] { "vwcygm", "herqgqi" }));
		towers.add(new Tower("odckjtb", 72));
		towers.add(new Tower("tdniuai", 39));
		towers.add(new Tower("tohrp", 65));
		towers.add(new Tower("wryfov", 57));
		towers.add(new Tower("vhrtptr", 139, new String[] { "bpqhqbg", "pacsxn" }));
		towers.add(new Tower("ohrraic", 94));
		towers.add(new Tower("eyale", 97));
		towers.add(new Tower("beraw", 14));
		towers.add(new Tower("mfywm", 79, new String[] { "erkarx", "vscjrx" }));
		towers.add(new Tower("knpwsi", 261, new String[] { "cvgbj", "uzjejte" }));
		towers.add(new Tower("wjyreb", 41, new String[] { "rabxkov", "rxqfv", "gcomv" }));
		towers.add(new Tower("rdwkvr", 38));
		towers.add(new Tower("mmerpi", 5));
		towers.add(new Tower("cbgyk", 43));
		towers.add(new Tower("oxyof", 44));
		towers.add(new Tower("tjhmz", 51));
		towers.add(new Tower("zmqom", 42, new String[] { "grazu", "yxkldyi" }));
		towers.add(new Tower("rxanas", 210, new String[] { "ctfjb", "ifbxvs" }));
		towers.add(new Tower("lynvd", 42593, new String[] { "tuieolg", "pddteg", "pixmx" }));
		towers.add(new Tower("scaec", 96));
		towers.add(new Tower("zbcra", 38, new String[] { "rjeunph", "edkigpl" }));
		towers.add(new Tower("ciogjt", 375, new String[] { "tygnc", "vhrtptr", "ccckie" }));
		towers.add(new Tower("uvsny", 44));
		towers.add(new Tower("mpgixa", 110, new String[] { "bmmmp", "btxepbv" }));
		towers.add(new Tower("aqkdlo", 24));
		towers.add(new Tower("yjxyb", 77, new String[] { "tceog", "pqnte", "yxxpgv", "aokpx" }));
		towers.add(new Tower("tlayc", 77));
		towers.add(new Tower("kjlmdi", 96));
		towers.add(new Tower("rqhhyc", 214, new String[] { "cizehi", "sqypc" }));
		towers.add(new Tower("tgkusb", 32));
		towers.add(new Tower("xguhm", 102, new String[] { "syyfs", "hpeaki", "fynniwm" }));
		towers.add(new Tower("koane", 8, new String[] { "rawuoi", "hkjwio", "vpynuf", "exxcrj", "ljhtov", "pwdpe", "bdymucv" }));
		towers.add(new Tower("phmtqf", 175, new String[] { "aodnlv", "jancm" }));
		towers.add(new Tower("rjguqr", 183, new String[] { "fgdqr", "ccsrkny" }));
		towers.add(new Tower("mnhojtk", 218, new String[] { "kvdrnf", "nkjgwn" }));
		towers.add(new Tower("ejuiv", 31));
		towers.add(new Tower("rijipom", 107, new String[] { "ijmfnt", "ymduw", "vdpmvm", "njeff" }));
		towers.add(new Tower("bbfaxid", 138));
		towers.add(new Tower("yoqbgjb", 25));
		towers.add(new Tower("bymzb", 68, new String[] { "zneumoh", "zhopeqm" }));
		towers.add(new Tower("qntstgd", 103, new String[] { "bbkfiz", "zonni" }));
		towers.add(new Tower("ahqfoz", 52));
		towers.add(new Tower("gfqtz", 98));
		towers.add(new Tower("yvxuom", 154, new String[] { "jbbmcxg", "ppiiyuy" }));
		towers.add(new Tower("zxkvs", 12, new String[] { "bclicjl", "yfruc", "axikbt", "nglji" }));
		towers.add(new Tower("vwojb", 97, new String[] { "qeubhb", "kkdaw", "ucfhxsv", "rythrvz" }));
		towers.add(new Tower("akpnwc", 90));
		towers.add(new Tower("rawuoi", 166, new String[] { "dzouqwl", "vztyfp", "dqgivj", "cssov" }));
		towers.add(new Tower("eggmj", 77));
		towers.add(new Tower("isggu", 5));
		towers.add(new Tower("jszpe", 39));
		towers.add(new Tower("kmarvbs", 90));
		towers.add(new Tower("btxepbv", 90));
		towers.add(new Tower("hjjfdj", 11));
		towers.add(new Tower("sfrbkzf", 45, new String[] { "tgmle", "mddejh", "tulxgem", "ofidu", "mjaol", "dhqzt" }));
		towers.add(new Tower("ibvaekj", 9));
		towers.add(new Tower("leegl", 94));
		towers.add(new Tower("lfjtmkg", 6095, new String[] { "lsteeu", "zxkvs", "sdhqlxw" }));
		towers.add(new Tower("itttb", 90));
		towers.add(new Tower("wlajxb", 201, new String[] { "tgyavjg", "eszxg" }));
		towers.add(new Tower("jlvwibm", 46));
		towers.add(new Tower("hcqnhm", 58));
		towers.add(new Tower("iqygrur", 44));
		towers.add(new Tower("bqifoq", 55));
		towers.add(new Tower("fovkc", 49));
		towers.add(new Tower("aozygag", 125));
		towers.add(new Tower("prcjhey", 92));
		towers.add(new Tower("fetkt", 203, new String[] { "nnhsuja", "kxflpnl", "xumsm" }));
		towers.add(new Tower("qjzol", 15));
		towers.add(new Tower("rufvv", 162, new String[] { "qzcbtes", "xekimqs" }));
		towers.add(new Tower("dhlrq", 88));
		towers.add(new Tower("mwztduj", 75));
		towers.add(new Tower("ydumax", 61));
		towers.add(new Tower("boygd", 13, new String[] { "wiayzvp", "mdhhd", "jkqvg", "wouprxh" }));
		towers.add(new Tower("uyrght", 80, new String[] { "hvcii", "lxhkgs" }));
		towers.add(new Tower("nglji", 311, new String[] { "cfaniht", "anbcmt" }));
		towers.add(new Tower("pfutotv", 44));
		towers.add(new Tower("zvwkjew", 60));
		towers.add(new Tower("miftchq", 21));
		towers.add(new Tower("xaatl", 56147, new String[] { "dgjls", "qoiuwmf", "koane", "fnoteku", "pavwo", "hpowmso", "yehxck" }));
		towers.add(new Tower("oejqkp", 13));
		towers.add(new Tower("oewlch", 659, new String[] { "tgffx", "eiwjrxx", "ksybvgt" }));
		towers.add(new Tower("dwpqell", 35));
		towers.add(new Tower("mnksdxf", 138));
		towers.add(new Tower("obfet", 87, new String[] { "iolmgs", "piouhkc" }));
		towers.add(new Tower("kazqnjr", 391, new String[] { "qngfv", "aacegb" }));
		towers.add(new Tower("kmogwi", 1139, new String[] { "hkjtym", "tgujvov", "dkttrfw" }));
		towers.add(new Tower("behncf", 16));
		towers.add(new Tower("ofosgz", 80));
		towers.add(new Tower("xejner", 239, new String[] { "jmlznjh", "foyfb", "pxihdrd" }));
		towers.add(new Tower("ylyef", 30));
		towers.add(new Tower("lqumiws", 88));
		towers.add(new Tower("jancm", 58));
		towers.add(new Tower("rdkvtq", 77));
		towers.add(new Tower("alztgi", 32));
		towers.add(new Tower("myhrxc", 16));
		towers.add(new Tower("ycctk", 1381, new String[] { "qtgibw", "lkorngt", "mufnw" }));
		towers.add(new Tower("wfovakv", 48, new String[] { "lppvxfk", "tznwmc", "utgxfsh", "zyympz", "asbzj", "ijcojo" }));
		towers.add(new Tower("lhsccbq", 42));
		towers.add(new Tower("tglnkgk", 81, new String[] { "wrxiwgy", "wrfxdc" }));
		towers.add(new Tower("ptkqcl", 41));
		towers.add(new Tower("cipgxee", 72));
		towers.add(new Tower("ecjdzpq", 35));
		towers.add(new Tower("ykpdiav", 51));
		towers.add(new Tower("wdjzjlk", 1631, new String[] { "iplyhhc", "pgchejz", "kwmam" }));
		towers.add(new Tower("ymhxg", 48, new String[] { "vohta", "ohplzu", "edpjix" }));
		towers.add(new Tower("vuetjdb", 157, new String[] { "pbxjvnl", "jdzbqlz", "xhnmlcw", "vipurf" }));
		towers.add(new Tower("skpcerk", 88));
		towers.add(new Tower("hfvhp", 2018, new String[] { "wewzb", "opmmmd", "zmqom" }));
		towers.add(new Tower("afrywlt", 80));
		towers.add(new Tower("amrbhgv", 126, new String[] { "xpker", "gkkrlg", "jbzaips" }));
		towers.add(new Tower("qsrpqe", 236, new String[] { "brztp", "kwwsxez" }));
		towers.add(new Tower("cdpfk", 92));
		towers.add(new Tower("oksoj", 51));
		towers.add(new Tower("eiwjrxx", 45, new String[] { "hbsmlf", "dlabh", "rcjxcou" }));
		towers.add(new Tower("pzewv", 23));
		towers.add(new Tower("zonni", 11));
		towers.add(new Tower("nkssh", 38));
		towers.add(new Tower("nmvvgr", 34));
		towers.add(new Tower("iteizf", 21));
		towers.add(new Tower("dvfuz", 30));
		towers.add(new Tower("scmiv", 54));
		towers.add(new Tower("qqishhq", 14));
		towers.add(new Tower("egsil", 38));
		towers.add(new Tower("iipqh", 299));
		towers.add(new Tower("icqjyqd", 16));
		towers.add(new Tower("zktnjab", 87));
		towers.add(new Tower("nkskfx", 94));
		towers.add(new Tower("leulsg", 44696, new String[] { "tifqyde", "olkopyn", "lfjtmkg" }));
		towers.add(new Tower("eskdbe", 17));
		towers.add(new Tower("dkhuccj", 96, new String[] { "kbyot", "zhbiaq", "hhmavd", "xejner", "cqlwzk" }));
		towers.add(new Tower("mkyam", 372));
		towers.add(new Tower("wxixtqj", 37));
		towers.add(new Tower("ilxfa", 34));
		towers.add(new Tower("woczl", 60, new String[] { "okseah", "afeqhu", "cnnrj", "cmaxybh" }));
		towers.add(new Tower("rjnzany", 44));
		towers.add(new Tower("lppvxfk", 1001, new String[] { "nrnmjo", "phmtqf", "bqznix" }));
		towers.add(new Tower("uzjxd", 196, new String[] { "zfnoo", "wlaslo", "tijkvua" }));
		towers.add(new Tower("ekihql", 1184, new String[] { "ezxsv", "vonzkut", "dkyswuu", "uyrght", "uzjxd", "yjomyth" }));
		towers.add(new Tower("rljjjo", 192, new String[] { "sobzsd", "ykljt" }));
		towers.add(new Tower("mfjeyx", 49, new String[] { "tdniuai", "vdjmhb" }));
		towers.add(new Tower("qjdpk", 28, new String[] { "wzxei", "jopyit" }));
		towers.add(new Tower("liamld", 25));
		towers.add(new Tower("rjeunph", 18));
		towers.add(new Tower("vscjrx", 79));
		towers.add(new Tower("gwyfm", 287, new String[] { "liamld", "ucqdz" }));
		towers.add(new Tower("gnmydtk", 67));
		towers.add(new Tower("xspxxb", 71));
		towers.add(new Tower("mwirmq", 188, new String[] { "mnpvutr", "dmvjz" }));
		towers.add(new Tower("myonh", 49));
		towers.add(new Tower("mupbrv", 218, new String[] { "phkwq", "hrjgaqj", "bwvemo" }));
		towers.add(new Tower("kztkiqt", 13, new String[] { "egsil", "mjugqpu" }));
		towers.add(new Tower("khpat", 53));
		towers.add(new Tower("wchlcja", 190));
		towers.add(new Tower("tjffhqh", 84));
		towers.add(new Tower("geqwvx", 129, new String[] { "acxlck", "zqnmsyb", "ojnziip" }));
		towers.add(new Tower("ufyavk", 1838, new String[] { "vunam", "kmarvbs", "kzdugfh" }));
		towers.add(new Tower("nvlxqp", 58));
		towers.add(new Tower("izhdt", 57, new String[] { "gfqtz", "sztqzfl" }));
		towers.add(new Tower("zfhxg", 345, new String[] { "srneoo", "ygmhxm", "epumc" }));
		towers.add(new Tower("wkhggv", 25));
		towers.add(new Tower("jjvxxtt", 194, new String[] { "ldfsxw", "mhkcp" }));
		towers.add(new Tower("mhzgkxx", 156, new String[] { "qzakfh", "tnayomw" }));
		towers.add(new Tower("bchlcqs", 53));
		towers.add(new Tower("ymduw", 28));
		towers.add(new Tower("grazu", 90));
		towers.add(new Tower("fgdqr", 34));
		towers.add(new Tower("swrkuc", 199, new String[] { "gylsj", "cyzzsc", "blmfs", "aonfaf" }));
		towers.add(new Tower("zrpqdzn", 62));
		towers.add(new Tower("dkyswuu", 120, new String[] { "zjzoo", "bhxdhmr" }));
		towers.add(new Tower("mjugqpu", 38));
		towers.add(new Tower("gijtd", 75));
		towers.add(new Tower("huhoda", 191, new String[] { "bpphw", "eqsxuaq", "gmwtl" }));
		towers.add(new Tower("vdkxk", 90, new String[] { "hrvztx", "fjhqmnv" }));
		towers.add(new Tower("huunb", 88));
		towers.add(new Tower("stiln", 72));
		towers.add(new Tower("exxcrj", 316, new String[] { "dzjyzd", "pkoww" }));
		towers.add(new Tower("bdymucv", 304, new String[] { "uzsytm", "sslltlv" }));
		towers.add(new Tower("dyscpqo", 49));
		towers.add(new Tower("tremw", 94));
		towers.add(new Tower("uotzz", 61, new String[] { "xyxtm", "cdpfk", "qmqrpcl" }));
		towers.add(new Tower("vlpop", 64, new String[] { "hshyx", "tchbf" }));
		towers.add(new Tower("rdmggka", 18));
		towers.add(new Tower("owigu", 9));
		towers.add(new Tower("bpqhqbg", 63));
		towers.add(new Tower("aeyykn", 66, new String[] { "lrkfnoy", "ltdrusl" }));
		towers.add(new Tower("kwwsxez", 27));
		towers.add(new Tower("jgtpw", 84, new String[] { "cxnjv", "zelucu", "ygurya", "mrsrl" }));
		towers.add(new Tower("oljci", 892, new String[] { "asifeu", "aoehbj", "oqjkafl" }));
		towers.add(new Tower("xqgwwr", 23));
		towers.add(new Tower("ctfjb", 20));
		towers.add(new Tower("cxnjv", 66));
		towers.add(new Tower("nrnmjo", 105, new String[] { "pzjbbdd", "nvvxl" }));
		towers.add(new Tower("wydbqai", 65, new String[] { "ryulu", "ydumax" }));
		towers.add(new Tower("ghdime", 76));
		towers.add(new Tower("cnvyxm", 59));
		towers.add(new Tower("xffvy", 59));
		towers.add(new Tower("qtgibw", 52, new String[] { "ovvrx", "ziypsz" }));
		towers.add(new Tower("ukkaxy", 211));
		towers.add(new Tower("yurfpj", 65));
		towers.add(new Tower("qvvcx", 41));
		towers.add(new Tower("ygurya", 66));
		towers.add(new Tower("zchulv", 72, new String[] { "cmxulaj", "tetdx", "huhoda", "blagy", "wgypwo" }));
		towers.add(new Tower("rqzfef", 86));
		towers.add(new Tower("drgtn", 84));
		towers.add(new Tower("goxfpk", 6));
		towers.add(new Tower("bcjecw", 80));
		towers.add(new Tower("njabgq", 57));
		towers.add(new Tower("gcwcs", 93, new String[] { "dokgk", "epsjj" }));
		towers.add(new Tower("fhzhqie", 65));
		towers.add(new Tower("ccsrkny", 34));
		towers.add(new Tower("onlwq", 59, new String[] { "ekxxsqa", "jlfho", "ekabfx" }));
		towers.add(new Tower("ldnrw", 760, new String[] { "plumb", "yvhilh", "kztkiqt", "ltbpi" }));
		towers.add(new Tower("nnxfo", 63, new String[] { "xffvy", "zqmlv", "krcoaft", "iimfrx" }));
		towers.add(new Tower("mrsrl", 66));
		towers.add(new Tower("vztyfp", 57));
		towers.add(new Tower("pacsxn", 63));
		towers.add(new Tower("maiimn", 77));
		towers.add(new Tower("usodrg", 53));
		towers.add(new Tower("rzphpv", 48));
		towers.add(new Tower("pavwo", 1890, new String[] { "mofkvq", "fmxtg", "rijipom", "mgqfa" }));
		towers.add(new Tower("gcomv", 84));
		towers.add(new Tower("pjxqt", 46));
		towers.add(new Tower("oywob", 47, new String[] { "ynayo", "ixxkvtz" }));
		towers.add(new Tower("fovilf", 44));
		towers.add(new Tower("ypsme", 11966, new String[] { "zfkfhfn", "fiufzkb", "ubgrma", "puurcu" }));
		towers.add(new Tower("etyyw", 11));
		towers.add(new Tower("ccityq", 34));
		towers.add(new Tower("hrjgaqj", 29));
		towers.add(new Tower("dhqzt", 305, new String[] { "capxp", "pttij" }));
		towers.add(new Tower("dpdjpal", 42));
		towers.add(new Tower("fbqpk", 38));
		towers.add(new Tower("qkrydu", 1886, new String[] { "leyiz", "mwirmq", "hhwngc" }));
		towers.add(new Tower("mufrkl", 60, new String[] { "wyomko", "lafoho", "rxanas", "vlpop", "ulvncs", "padxpdx" }));
		towers.add(new Tower("cssov", 57));
		towers.add(new Tower("wgeig", 15));
		towers.add(new Tower("rythrvz", 65));
		towers.add(new Tower("juptypm", 14));
		towers.add(new Tower("dxympe", 23));
		towers.add(new Tower("ckwooig", 84));
		towers.add(new Tower("zgimdwb", 107, new String[] { "znucug", "mrigsjh" }));
		towers.add(new Tower("bbhyth", 53, new String[] { "xcqwjrm", "kgmwfq" }));
		towers.add(new Tower("vyriv", 50, new String[] { "vwbjuvx", "xergqq", "wlpfcsr" }));
		towers.add(new Tower("qzcbtes", 65));
		towers.add(new Tower("kgmwfq", 63));
		towers.add(new Tower("losdis", 1165, new String[] { "vhmijln", "lteyo", "viufoq" }));
		towers.add(new Tower("iplyhhc", 122, new String[] { "cbgyk", "dzohgiq" }));
		towers.add(new Tower("fpqudx", 187, new String[] { "iuxgzr", "icqjyqd", "apmdcz", "mhapqqy" }));
		towers.add(new Tower("jaxidl", 86));
		towers.add(new Tower("xhyqtqz", 77, new String[] { "swrkuc", "ncfuru", "kazqnjr" }));
		towers.add(new Tower("rznnmp", 70));
		towers.add(new Tower("jvhxfl", 39));
		towers.add(new Tower("gxzkde", 65));
		towers.add(new Tower("uiwaf", 97));
		towers.add(new Tower("cfnce", 59));
		towers.add(new Tower("fkgxak", 328, new String[] { "wpnqifq", "xbucnh", "qjwfsfk", "rcsfkrb" }));
		towers.add(new Tower("nrcbc", 98));
		towers.add(new Tower("aodnlv", 58));
		towers.add(new Tower("yvhilh", 89));
		towers.add(new Tower("cyzzsc", 52));
		towers.add(new Tower("pjedtl", 55));
		towers.add(new Tower("bvrlaep", 143, new String[] { "dnrfjv", "wndpfac", "bezvr" }));
		towers.add(new Tower("clpekkm", 77));
		towers.add(new Tower("wnyxznj", 65));
		towers.add(new Tower("wonxzkm", 57));
		towers.add(new Tower("vifwkwa", 173, new String[] { "zvwkjew", "txkgx", "vvqpffs" }));
		towers.add(new Tower("qroirmg", 45));
		towers.add(new Tower("mdzkkjf", 22));
		towers.add(new Tower("pmfkdn", 14));
		towers.add(new Tower("qgfstpq", 12));
		towers.add(new Tower("mhydkla", 7));
		towers.add(new Tower("yekjlfd", 106, new String[] { "ecjdzpq", "dcmxxd" }));
		towers.add(new Tower("gxiwcqv", 186, new String[] { "zfhwfsw", "lovypfn" }));
		towers.add(new Tower("ifbxvs", 20));
		towers.add(new Tower("lwwyx", 41, new String[] { "vuetjdb", "ciejakr", "imjutr", "zgimdwb", "sdnlegj", "gzixhdc", "tlvkwlx" }));
		towers.add(new Tower("tfdbdq", 22));
		towers.add(new Tower("dzggd", 663, new String[] { "iipqh", "nnxfo", "veggtf" }));
		towers.add(new Tower("xwltxk", 2001, new String[] { "yirnxk", "baawtw", "msfxkn" }));
		towers.add(new Tower("tznwmc", 1199, new String[] { "dnfvldg", "dbufjl", "pnhibed" }));
		towers.add(new Tower("uiioczf", 130));
		towers.add(new Tower("rcjxcou", 56));
		towers.add(new Tower("tatubv", 205));
		towers.add(new Tower("vvqpffs", 60));
		towers.add(new Tower("bugwblt", 14));
		towers.add(new Tower("umtfn", 80, new String[] { "hbylau", "dzrkq", "rugltaa" }));
		towers.add(new Tower("cqlwzk", 217, new String[] { "besihsl", "cwdmlj" }));
		towers.add(new Tower("pxteg", 56, new String[] { "odkzxae", "gcxrx", "cotpovw" }));
		towers.add(new Tower("nbivp", 106, new String[] { "ndnku", "gjcxbx", "iqygrur", "oxyof" }));
		towers.add(new Tower("twvib", 18));
		towers.add(new Tower("fyzeso", 57));
		towers.add(new Tower("nlndxah", 11));
		towers.add(new Tower("wolet", 91));
		towers.add(new Tower("pixmx", 4482, new String[] { "hrgbkby", "bvfcsls", "tzvawqb", "jfdscql", "gqggcxb" }));
		towers.add(new Tower("ctytfj", 29));
		towers.add(new Tower("lwaeqm", 83));
		towers.add(new Tower("cnbekc", 92));
		towers.add(new Tower("ekzvjj", 35));
		towers.add(new Tower("zgssy", 67));
		towers.add(new Tower("hbylau", 94));
		towers.add(new Tower("yonjpz", 62));
		towers.add(new Tower("btcjg", 57));
		towers.add(new Tower("tdbne", 72));
		towers.add(new Tower("edkigpl", 18));
		towers.add(new Tower("amnoi", 141, new String[] { "noxvvva", "dfeyr" }));
		towers.add(new Tower("gwtcgyo", 24));
		towers.add(new Tower("zrnlo", 42));
		towers.add(new Tower("ndnku", 44));
		towers.add(new Tower("etwwy", 16));
		towers.add(new Tower("hsoxt", 62));
		towers.add(new Tower("kdqjj", 16));
		towers.add(new Tower("cgouh", 26));
		towers.add(new Tower("mnvgaqh", 128, new String[] { "jntohm", "vobeup", "ptkqcl" }));
		towers.add(new Tower("ocgkcxp", 13));
		towers.add(new Tower("ayaouxu", 200, new String[] { "ksyewek", "gpfrztg" }));
		towers.add(new Tower("baawtw", 50, new String[] { "nnguamj", "yetcvhx" }));
		towers.add(new Tower("ykljt", 13));
		towers.add(new Tower("znucug", 55));
		towers.add(new Tower("ypqxs", 31));
		towers.add(new Tower("pmgrf", 21));
		towers.add(new Tower("anmeg", 58));
		towers.add(new Tower("fmxtg", 84, new String[] { "ursjc", "eqhxqxm", "qroirmg" }));
		towers.add(new Tower("dgjls", 1926, new String[] { "lgxjr", "hrphtyk", "mhzgkxx" }));
		towers.add(new Tower("prxseo", 16));
		towers.add(new Tower("vhxlart", 70));
		towers.add(new Tower("zyniqni", 147, new String[] { "khqhd", "zrnlo" }));
		towers.add(new Tower("dtexqt", 88));
		towers.add(new Tower("mqybmn", 86));
		towers.add(new Tower("pljyyn", 73));
		towers.add(new Tower("jzibybz", 248, new String[] { "zrpqdzn", "hsoxt" }));
		towers.add(new Tower("dokgk", 17));
		towers.add(new Tower("bclicjl", 217, new String[] { "dxufd", "jhcsmc" }));
		towers.add(new Tower("tlvkwlx", 133, new String[] { "fjpgybt", "miftchq", "oyfma", "ytivjxk" }));
		towers.add(new Tower("qsqis", 1208, new String[] { "aovlz", "mxusu" }));
		towers.add(new Tower("mhkba", 21));
		towers.add(new Tower("kvdrnf", 72));
		towers.add(new Tower("fcpde", 175, new String[] { "beraw", "qqishhq", "citugfl", "pmfkdn" }));
		towers.add(new Tower("jcpavmj", 53));
		towers.add(new Tower("bbkfiz", 11));
		towers.add(new Tower("wqbhby", 15));
		towers.add(new Tower("mfvkd", 21));
		towers.add(new Tower("hhifd", 6));
		towers.add(new Tower("ibonrqn", 50));
		towers.add(new Tower("jzuvrtp", 57));
		towers.add(new Tower("zelucu", 66));
		towers.add(new Tower("zneumoh", 80));
		towers.add(new Tower("ljhtov", 394));
		towers.add(new Tower("okmqiy", 46));
		towers.add(new Tower("cmaxybh", 78));
		towers.add(new Tower("phkwq", 29));
		towers.add(new Tower("mvfhc", 420, new String[] { "wchlcja", "ikfihh", "ybnvm", "cztikzk", "qhmyi", "uebnns" }));
		towers.add(new Tower("jzsmy", 39));
		towers.add(new Tower("edpjix", 58));
		towers.add(new Tower("myaiu", 129, new String[] { "pqmrmke", "iizbmoz", "rhkbrsr", "apwsmv" }));
		towers.add(new Tower("mnkqevh", 98));
		towers.add(new Tower("noxvvva", 94));
		towers.add(new Tower("ncfuru", 87, new String[] { "bcjecw", "kybsigz", "mtcxdod", "ofosgz" }));
		towers.add(new Tower("pttij", 68));
		towers.add(new Tower("eutcl", 77));
		towers.add(new Tower("mzwbtsa", 119, new String[] { "eceocsy", "ecoqyk" }));
		towers.add(new Tower("wrxiwgy", 25));
		towers.add(new Tower("fydjnl", 32));
		towers.add(new Tower("bsixe", 80));
		towers.add(new Tower("oxcuf", 80, new String[] { "crobb", "xpfxwd" }));
		towers.add(new Tower("yqnihs", 56, new String[] { "wqoucl", "rsqyvy", "zetvslt" }));
		towers.add(new Tower("mqhkd", 100, new String[] { "pjhry", "ljhxxd" }));
		towers.add(new Tower("bwvemo", 29));
		towers.add(new Tower("hbsmlf", 56));
		towers.add(new Tower("sduuog", 9));
		towers.add(new Tower("nnguamj", 71));
		towers.add(new Tower("xrhsy", 266, new String[] { "qbrrjg", "juptypm", "bugwblt" }));
		towers.add(new Tower("rxqfv", 84));
		towers.add(new Tower("bqqwmry", 73));
		towers.add(new Tower("gyutarg", 51, new String[] { "adbolgz", "vdvadz" }));
		towers.add(new Tower("vyozfv", 99));
		towers.add(new Tower("njrfnvt", 96));
		towers.add(new Tower("ruxnrix", 35));
		towers.add(new Tower("sgieno", 107, new String[] { "miijab", "zryrfnw" }));
		towers.add(new Tower("vpynuf", 214, new String[] { "akpnwc", "rulhhsl" }));
		towers.add(new Tower("mkbgt", 98));
		towers.add(new Tower("iwyjkz", 86));
		towers.add(new Tower("itxycu", 45, new String[] { "eutcl", "kdevmnr" }));
		towers.add(new Tower("ytspbx", 184, new String[] { "nkskfx", "ohrraic" }));
		towers.add(new Tower("ayejq", 86));
		towers.add(new Tower("fhpaqmd", 23));
		towers.add(new Tower("jjqguew", 24));
		towers.add(new Tower("mnfqc", 789, new String[] { "zqtkn", "hhqlfj", "lywkfsn" }));
		towers.add(new Tower("aplbnbx", 28));
		towers.add(new Tower("hshyx", 93));
		towers.add(new Tower("ozfzz", 11));
		towers.add(new Tower("rhbouej", 181, new String[] { "udkyxw", "rzphpv" }));
		towers.add(new Tower("wchxl", 67));
		towers.add(new Tower("inghbu", 1167, new String[] { "vcvypf", "ljqmiu", "tglnkgk" }));
		towers.add(new Tower("fticuc", 1360, new String[] { "vleydj", "lnczb", "igpabio", "wydbqai" }));
		towers.add(new Tower("ivwcuc", 88));
		towers.add(new Tower("peuppj", 29, new String[] { "oqrmida", "txxnutu", "fzqsahw" }));
		towers.add(new Tower("ppiiyuy", 34));
		towers.add(new Tower("mgkkyx", 77));
		towers.add(new Tower("akwfu", 50, new String[] { "tremw", "uwhjd" }));
		towers.add(new Tower("tceog", 70));
		towers.add(new Tower("acxlck", 73));
		towers.add(new Tower("woves", 32));
		towers.add(new Tower("veksns", 308, new String[] { "slhitu", "lghzki" }));
		towers.add(new Tower("ljhxxd", 38));
		towers.add(new Tower("dqgivj", 57));
		towers.add(new Tower("sdbksb", 171, new String[] { "hbkjjtt", "zxson" }));
		towers.add(new Tower("erfnrn", 6));
		towers.add(new Tower("nclwgga", 201));
		towers.add(new Tower("mdhhd", 28));
		towers.add(new Tower("rhzimzq", 74, new String[] { "drgtn", "raqjoxn" }));
		towers.add(new Tower("rqymw", 97));
		towers.add(new Tower("nkjgwn", 72));
		towers.add(new Tower("vwcygm", 36));
		towers.add(new Tower("acfyjc", 85));
		towers.add(new Tower("iajslqp", 32, new String[] { "avelbqj", "ebgdslc", "vzqnfs" }));
		towers.add(new Tower("dlhiqh", 7301, new String[] { "rdrad", "vmmjgy", "uvmqarq" }));
		towers.add(new Tower("koxiwk", 929, new String[] { "fcscdg", "geqwvx", "jgtpw", "zorvynv", "zotwsb" }));
		towers.add(new Tower("yjomyth", 97, new String[] { "oksoj", "lmwrf", "tjhmz" }));
		towers.add(new Tower("hhwngc", 138, new String[] { "ewpbnsk", "swurfm" }));
		towers.add(new Tower("ikdsvc", 1609, new String[] { "icjur", "ebmjz", "rxivjo", "rhzimzq" }));
		towers.add(new Tower("mewof", 12));
		towers.add(new Tower("bmugsve", 36));
		towers.add(new Tower("zcgfj", 78));
		towers.add(new Tower("dyimc", 54));
		towers.add(new Tower("iuxgzr", 16));
		towers.add(new Tower("fxasat", 57));
		towers.add(new Tower("ixkicz", 353));
		towers.add(new Tower("fvfek", 96));
		towers.add(new Tower("rycmr", 82));
		towers.add(new Tower("xfydt", 87));
		towers.add(new Tower("ybnvm", 50, new String[] { "dwpqell", "fmtyy", "bkcghv", "ekzvjj" }));
		towers.add(new Tower("abbnh", 33));
		towers.add(new Tower("pbxjvnl", 15));
		towers.add(new Tower("lrkfnoy", 78));
		towers.add(new Tower("lpbayb", 8));
		towers.add(new Tower("oeqvt", 19, new String[] { "grcox", "otplae" }));
		towers.add(new Tower("bdafpm", 58));
		towers.add(new Tower("upevl", 95));
		towers.add(new Tower("jijwa", 3632, new String[] { "xwltxk", "ikdsvc", "tcghqr" }));
		towers.add(new Tower("tgyavjg", 18));
		towers.add(new Tower("bwrpskq", 65));
		towers.add(new Tower("lhsncv", 67));
		towers.add(new Tower("kqaoir", 80, new String[] { "ytspbx", "dyrvvfn", "bkldmro", "qonfiro", "hhlxxzt", "jzibybz", "slrfd" }));
		towers.add(new Tower("dlabh", 56));
		towers.add(new Tower("drfwgmu", 249, new String[] { "zktnjab", "cmfkxo" }));
		towers.add(new Tower("qbrrjg", 14));
		towers.add(new Tower("tijkvua", 18));
		towers.add(new Tower("stkodp", 84));
		towers.add(new Tower("zunhob", 79));
		towers.add(new Tower("dnfvldg", 85, new String[] { "yjakrqa", "lahain" }));
		towers.add(new Tower("pjyld", 10676, new String[] { "zfhxg", "oenxsfm", "ciogjt", "ebmcu", "mnfqc", "zgqzrc", "pzksun" }));
		towers.add(new Tower("dxufd", 64));
		towers.add(new Tower("zryrfnw", 49));
		towers.add(new Tower("ycacj", 25));
		towers.add(new Tower("smmgkir", 31));
		towers.add(new Tower("bymkeq", 71));
		towers.add(new Tower("bzsiwp", 71));
		towers.add(new Tower("wqoucl", 99));
		towers.add(new Tower("njdmj", 73));
		towers.add(new Tower("tzvawqb", 1010, new String[] { "qirjqsm", "muksdck", "oxcuf" }));
		towers.add(new Tower("ljqmiu", 31, new String[] { "ibonrqn", "imezigo" }));
		towers.add(new Tower("pppxrv", 62));
		towers.add(new Tower("xbyjur", 14));
		towers.add(new Tower("hkjtym", 247, new String[] { "iwsjla", "thqkxpl" }));
		towers.add(new Tower("ucqdz", 25));
		towers.add(new Tower("ekxxsqa", 83));
		towers.add(new Tower("jbexk", 73));
		towers.add(new Tower("mkkpihe", 24));
		towers.add(new Tower("evcdf", 57));
		towers.add(new Tower("sobzsd", 13));
		towers.add(new Tower("rfohgya", 25));
		towers.add(new Tower("ahmitv", 11));
		towers.add(new Tower("wtyfb", 238));
		towers.add(new Tower("inldh", 4965, new String[] { "ogvod", "agliie", "wenii" }));
		towers.add(new Tower("mieecfc", 138, new String[] { "lwljcg", "acfyjc" }));
		towers.add(new Tower("yrlks", 44));
		towers.add(new Tower("gcbcyn", 289, new String[] { "vflyupn", "mbwenqu" }));
		towers.add(new Tower("xevhcxq", 86));
		towers.add(new Tower("xayglgm", 21));
		towers.add(new Tower("hdlovco", 5));
		towers.add(new Tower("awagc", 18));
		towers.add(new Tower("zqnul", 38));
		towers.add(new Tower("rhkbrsr", 31));
		towers.add(new Tower("ejzeqxz", 51));
		towers.add(new Tower("onogiv", 30));
		towers.add(new Tower("ltdrusl", 78));
		towers.add(new Tower("yzptgez", 29));
		towers.add(new Tower("bkldmro", 212, new String[] { "bsixe", "afrywlt" }));
		towers.add(new Tower("zksmijj", 189, new String[] { "zsvuw", "hjjfdj" }));
		towers.add(new Tower("pqmrmke", 31));
		towers.add(new Tower("gzixhdc", 124, new String[] { "ypqxs", "setrric", "smmgkir" }));
		towers.add(new Tower("ytivjxk", 21));
		towers.add(new Tower("wiayzvp", 28));
		towers.add(new Tower("hbkjjtt", 61));
		towers.add(new Tower("rhdudt", 83));
		towers.add(new Tower("eqhxqxm", 45));
		towers.add(new Tower("gpfrztg", 54));
		towers.add(new Tower("slrfd", 340, new String[] { "etwwy", "qldijf" }));
		towers.add(new Tower("iolmgs", 95));
		towers.add(new Tower("ckhip", 88, new String[] { "vhxlart", "rznnmp" }));
		towers.add(new Tower("pcdjo", 63));
		towers.add(new Tower("ojnziip", 73));
		towers.add(new Tower("nvdouwn", 161, new String[] { "llibmc", "jkfob", "dyscpqo" }));
		towers.add(new Tower("gbnxgny", 12));
		towers.add(new Tower("vzqnfs", 31));
		towers.add(new Tower("lixqwd", 35));
		towers.add(new Tower("crobb", 8));
		towers.add(new Tower("vdbihjp", 69));
		towers.add(new Tower("llibmc", 49));
		towers.add(new Tower("lkorngt", 132, new String[] { "tjpatnk", "nmstp" }));
		towers.add(new Tower("ecxfenj", 78, new String[] { "urjwj", "jesiypo" }));
		towers.add(new Tower("ekabfx", 83));
		towers.add(new Tower("opqoq", 648, new String[] { "mjlnaz", "bymzb", "lmqaxz", "lageym" }));
		towers.add(new Tower("yfruc", 303, new String[] { "pmgrf", "hsfjd" }));
		towers.add(new Tower("fkbrmim", 71889, new String[] { "peuppj", "uobgj", "llventw", "duepwu" }));
		towers.add(new Tower("nzwxd", 103, new String[] { "wykkwa", "oydxsh", "bozlg" }));
		towers.add(new Tower("kcuygjx", 71));
		towers.add(new Tower("hvcii", 85));
		towers.add(new Tower("fjhqmnv", 57));
		towers.add(new Tower("txxnutu", 97, new String[] { "bcyarwn", "uteosk", "kjjyu" }));
		towers.add(new Tower("hrgbkby", 53, new String[] { "saowgr", "lprmau", "ntabiof" }));
		towers.add(new Tower("xhnmlcw", 15));
		towers.add(new Tower("clnkvox", 33));
		towers.add(new Tower("bhwca", 76));
		towers.add(new Tower("uojcup", 985, new String[] { "ttnnyy", "yekjlfd", "pdxylvu", "fjzpjk", "mqhkd", "ibiwh" }));
		towers.add(new Tower("mxusu", 45));
		towers.add(new Tower("ixxkvtz", 71));
		towers.add(new Tower("gqggcxb", 29, new String[] { "tzrppo", "bugfhhx", "drfwgmu" }));
		towers.add(new Tower("bsrkr", 21));
		towers.add(new Tower("erkarx", 79));
		towers.add(new Tower("kabcmf", 51));
		towers.add(new Tower("tknmww", 92));
		towers.add(new Tower("qgvsuqv", 206, new String[] { "jhgsgy", "enbnfw", "uflldd", "jvhxfl" }));
		towers.add(new Tower("cfaniht", 17));
		towers.add(new Tower("jrgwnfh", 57));
		towers.add(new Tower("rdmrzdv", 99));
		towers.add(new Tower("krcoaft", 59));
		towers.add(new Tower("ifelr", 77));
		towers.add(new Tower("hpaggeh", 88));
		towers.add(new Tower("wlaslo", 18));
		towers.add(new Tower("wouprxh", 28));
		towers.add(new Tower("hhmavd", 359, new String[] { "pxzdv", "qjzol" }));
		towers.add(new Tower("bqmqbi", 47));
		towers.add(new Tower("aokpx", 70));
		towers.add(new Tower("lteyo", 157, new String[] { "mfvkd", "swpfak" }));
		towers.add(new Tower("hrphtyk", 19, new String[] { "xjcprt", "bbzmsv", "berje" }));
		towers.add(new Tower("pkoww", 39));
		towers.add(new Tower("jsjaxjk", 88, new String[] { "aidknm", "uiwaf" }));
		towers.add(new Tower("uebnns", 127, new String[] { "iteizf", "lzxrfk", "tlfsn" }));
		towers.add(new Tower("wcevmtt", 77));
		towers.add(new Tower("yxkldyi", 90));
		towers.add(new Tower("qpefm", 823, new String[] { "kmogwi", "ufyavk", "evnlr", "rmlddp", "fticuc" }));
		towers.add(new Tower("cmfkxo", 87));
		towers.add(new Tower("qldijf", 16));
		towers.add(new Tower("nstdz", 65));
		towers.add(new Tower("aoehbj", 182, new String[] { "dyimc", "scmiv" }));
		towers.add(new Tower("eceocsy", 35));
		towers.add(new Tower("hwrxn", 53, new String[] { "dihzy", "ibysnvc", "zunhob" }));
		towers.add(new Tower("nglea", 50, new String[] { "pfutotv", "yrlks" }));
		towers.add(new Tower("fmqjogk", 24));
		towers.add(new Tower("tgblta", 141, new String[] { "elmog", "woves" }));
		towers.add(new Tower("jkfob", 49));
		towers.add(new Tower("vcvypf", 113, new String[] { "mttvnpg", "sduuog" }));
		towers.add(new Tower("wlpfcsr", 99));
		towers.add(new Tower("lybovx", 18));
		towers.add(new Tower("mbwenqu", 34));
		towers.add(new Tower("obkhwze", 38));
		towers.add(new Tower("vleydj", 173, new String[] { "mhydkla", "msthql" }));
		towers.add(new Tower("uduan", 75));
		towers.add(new Tower("ykruy", 39));
		towers.add(new Tower("aiunuvn", 1629, new String[] { "gjrqs", "ukkaxy", "lijeejc", "zlgpmfs", "zksmijj" }));
		towers.add(new Tower("lqavsk", 73));
		towers.add(new Tower("afeqhu", 78));
		towers.add(new Tower("veggtf", 104, new String[] { "wnyxznj", "mnwefbn", "fhzhqie" }));
		towers.add(new Tower("jbbivz", 16));
		towers.add(new Tower("uzjejte", 48));
		towers.add(new Tower("jhysc", 274, new String[] { "cldbz", "cluxnul" }));
		towers.add(new Tower("vhmijln", 97, new String[] { "tmyhhql", "ykpdiav" }));
		towers.add(new Tower("nqvflzq", 61));
		towers.add(new Tower("cotpovw", 91));
		towers.add(new Tower("yookz", 5));
		towers.add(new Tower("skjtvyz", 18));
		towers.add(new Tower("szutvca", 32));
		towers.add(new Tower("navhthp", 136, new String[] { "rrywqx", "vjxmbzm" }));
		towers.add(new Tower("okseah", 78));
		towers.add(new Tower("ebmcu", 30, new String[] { "glsrg", "ckhip", "rqhhyc", "jjvxxtt", "rdnpoms" }));
		towers.add(new Tower("wuybunc", 54));
		towers.add(new Tower("oktfn", 37));
		towers.add(new Tower("tvnco", 63));
		towers.add(new Tower("tfpuqgs", 24));
		towers.add(new Tower("ijmfnt", 28));
		towers.add(new Tower("zswyy", 36));
		towers.add(new Tower("sqiac", 24));
		towers.add(new Tower("xbucnh", 11));
		towers.add(new Tower("zmpwz", 12));
		towers.add(new Tower("cotvk", 91));
		towers.add(new Tower("ohtply", 49));
		towers.add(new Tower("ysigfem", 177));
		towers.add(new Tower("jlfgvr", 72));
		towers.add(new Tower("kplegas", 86));
		towers.add(new Tower("mbezs", 71));
		towers.add(new Tower("rprjk", 205));
		towers.add(new Tower("jlfho", 83));
		towers.add(new Tower("melsryt", 58));
		towers.add(new Tower("oenxsfm", 275, new String[] { "cuhrgp", "qlgme", "bbhyth", "dnzdqz", "ezdhr" }));
		towers.add(new Tower("sdnlegj", 207, new String[] { "hdlovco", "mmerpi" }));
		towers.add(new Tower("dzouqwl", 57));
		towers.add(new Tower("rugltaa", 94));
		towers.add(new Tower("imezigo", 50));
		towers.add(new Tower("iizbmoz", 31));
		towers.add(new Tower("vipurf", 15));
		towers.add(new Tower("awufxne", 2141, new String[] { "qllluo", "wpoga" }));
		towers.add(new Tower("gkkrlg", 36));
		towers.add(new Tower("dfeyr", 94));
		towers.add(new Tower("zmlmsuf", 23));
		towers.add(new Tower("lzxrfk", 21));
		towers.add(new Tower("jhcsmc", 64));
		towers.add(new Tower("ksyewek", 54));
		towers.add(new Tower("jzcmf", 24));
		towers.add(new Tower("xumsm", 16));
		towers.add(new Tower("eiyxf", 32));
		towers.add(new Tower("intfltq", 33));
		towers.add(new Tower("yhyxv", 160, new String[] { "ahmitv", "ozfzz", "zcdzv", "rhlllw" }));
		towers.add(new Tower("jopyit", 51));
		towers.add(new Tower("rmlddp", 64, new String[] { "rufvv", "gxiwcqv", "cjcapa", "exwxepj", "qvbfob", "zimrsr", "nrcbij" }));
		towers.add(new Tower("dnazkh", 80));
		towers.add(new Tower("raqjoxn", 84));
		towers.add(new Tower("cgfykiv", 38));
		towers.add(new Tower("tygnc", 13, new String[] { "ucxedq", "jgwvp", "kgevjdx" }));
		towers.add(new Tower("ojhlp", 137, new String[] { "zqnul", "vmvxwar", "cgfykiv" }));
		towers.add(new Tower("hpuyku", 82));
		return towers;
	}
}
